version: '3'
services:
  bmux:
    build: .
    image: bmux
    shm_size: '2gb'
    stdin_open: true
    tty: true
    volumes:
      - /root/.gradle
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.ssh:/root/.ssh
      - ~:/work
